// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string | undefined)?.trim();
// Support both common env var names to avoid misconfig between local/dev/CI.
const SUPABASE_PUBLISHABLE_KEY = (
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ??
  (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined)
)?.trim();

// #region agent log (debug-mode)
try {
  fetch('http://127.0.0.1:7242/ingest/4dbc215f-e85a-47d5-88db-cdaf6c66d6aa', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      sessionId: 'debug-session',
      runId: 'pre-fix',
      hypothesisId: 'H1',
      location: 'src/integrations/supabase/client.ts:SUPABASE_CONFIG',
      message: 'Supabase config snapshot (web app)',
      data: {
        urlPresent: Boolean(SUPABASE_URL),
        urlHost: SUPABASE_URL ? new URL(SUPABASE_URL).host : null,
        keyPresent: Boolean(SUPABASE_PUBLISHABLE_KEY),
        keyLen: SUPABASE_PUBLISHABLE_KEY?.length ?? 0,
        configError: !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY,
        href: typeof location !== 'undefined' ? location.href : null,
      },
      timestamp: Date.now(),
    }),
  }).catch(() => {});
} catch {
  // ignore
}
// #endregion

export const supabaseConfig = {
  url: SUPABASE_URL,
  // Never expose the full key; this is only for basic debugging in UI.
  keyPreview: SUPABASE_PUBLISHABLE_KEY
    ? `${SUPABASE_PUBLISHABLE_KEY.slice(0, 6)}…${SUPABASE_PUBLISHABLE_KEY.slice(-6)}`
    : null,
};

export const supabaseConfigError =
  !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY
    ? "Missing Supabase config. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY)."
    : null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Avoid crashing the app at import-time if env vars are missing; UI should surface supabaseConfigError.
const SAFE_URL = SUPABASE_URL ?? "https://invalid.supabase.co";
const SAFE_KEY = SUPABASE_PUBLISHABLE_KEY ?? "invalid";

export const supabase = createClient<Database>(SAFE_URL, SAFE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});