// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string | undefined)?.trim();
// Support both common env var names to avoid misconfig between local/dev/CI.
const SUPABASE_PUBLISHABLE_KEY = (
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ??
  (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined)
)?.trim();

export const supabaseConfig = {
  url: SUPABASE_URL,
  // Never expose the full key; this is only for basic debugging in UI.
  keyPreview: SUPABASE_PUBLISHABLE_KEY
    ? `${SUPABASE_PUBLISHABLE_KEY.slice(0, 6)}…${SUPABASE_PUBLISHABLE_KEY.slice(-6)}`
    : null,
};

export const supabaseConfigError =
  !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY
    ? "Missing Supabase config. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY (or VITE_SUPABASE_ANON_KEY)."
    : null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Avoid crashing the app at import-time if env vars are missing; UI should surface supabaseConfigError.
const SAFE_URL = SUPABASE_URL ?? "https://invalid.supabase.co";
const SAFE_KEY = SUPABASE_PUBLISHABLE_KEY ?? "invalid";

export const supabase = createClient<Database>(SAFE_URL, SAFE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});